### ISSUE TITLE
files bug? example: qa.restricted: umsp

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/EdaSubsettingService#126]
the message in subsetting logs:
"No metadata file was found to parse binary properties from for variable EUPATH_0043203"
but the files seem to include the variable. 
so the message is unclear.

![file-variable-error](https://github.com/VEuPathDB/EdaSubsettingService/assets/16354313/d33b2972-83f5-4c98-b22a-ac934acb47ae)

**Comment by ryanrdoherty** [comment]
Backend error is:
```
Caused by: java.lang.IllegalStateException: No metadata file was found to parse binary properties from for variable EUPATH_0025072
	at org.veupathdb.service.eda.ss.model.variable.StringVariable.getBinaryConverter(StringVariable.java:37) ~[service.jar:3.9.0]
	at org.veupathdb.service.eda.ss.model.reducer.BinaryValuesStreamer.streamFilteredEntityIdIndexes(BinaryValuesStreamer.java:49) ~[service.jar:3.9.0]
	at org.veupathdb.service.eda.ss.model.filter.SingleValueFilter.streamFilteredIds(SingleValueFilter.java:49) ~[service.jar:3.9.0]
```

**Comment by ryanrdoherty** [comment]
Resolved by [this commit](https://github.com/VEuPathDB/lib-eda-subsetting/commit/43e668da5ac296945a7e9c5fee4f8e1838b70550).
