### ISSUE TITLE
Backend: GEMS1 Subset gives a 500

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaSubsettingService#32]
inspired by a post in slack from @bobular i tried actively making an empty subset. first attempt was this:
`curl -X POST -H "Content-type: application/json" -d '{"studyId":"GEMSCC0003-1","filters":[{"entityId":"EUPATH_0035127","variableId":"ENVO_00000009","stringSet":["India"],"type":"stringSet"},{"entityId":"PCO_0000024","variableId":"EUPATH_0000006","stringSet":["Finished floor; vinyl of asphalt strips"],"type":"stringSet"},{"variableId":"EUPATH_0015332","entityId":"EUPATH_0000609","type":"numberRange","min":31,"max":34}],"config":{"outputEntityId":"PCO_0000024","xAxisVariable":{"entityId":"PCO_0000024","variableId":"EUPATH_0000019"},"barMode":"stack","valueSpec":"count","binSpec":{"type":"binWidth"},"showMissingness":"FALSE"}}' http://localhost:8082/apps/pass/visualizations/histogram`

**Comment by d-callan** [comment]
gave me a stack in the subset service like:
`org.gusdb.fgputil.db.runner.SQLRunnerException: Unable to process result of SQL <SELECT distinct stable_id, data_type, data_shape, display_type, has_values, unit, is_multi_valued, precision, provider_label, display_name, parent_stable_id, definition, vocabulary, display_order, display_range_min, display_range_max, range_min, range_max, bin_width_override, bin_width_computed, is_temporal, is_featured, is_merge_key, is_repeated, distinct_values_count, is_multi_valued
FROM apidb.AttributeGraph_GEMSCC0003_1_Participant
ORDER BY stable_id> with args [ ]
	at org.gusdb.fgputil.db.runner.SQLRunner.executeSql(SQLRunner.java:403) ~[service.jar:1.0.0]
	at org.gusdb.fgputil.db.runner.SQLRunner.executeQuery(SQLRunner.java:323) ~[service.jar:1.0.0]
	at org.gusdb.fgputil.db.runner.SQLRunner.executeQuery(SQLRunner.java:310) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ss.model.VariableResultSetUtils.getEntityVariables(VariableResultSetUtils.java:67) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ss.model.Entity.loadVariables(Entity.java:171) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ss.model.Study.loadStudy(Study.java:57) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ss.model.MetadataCache.lambda$getStudy$0(MetadataCache.java:19) ~[service.jar:1.0.0]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]	at org.veupathdb.service.eda.ss.model.MetadataCache.getStudy(MetadataCache.java:18) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ss.service.StudiesService.getStudiesByStudyId(StudiesService.java:78) ~[service.jar:1.0.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) [service.jar:1.0.0]	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [service.jar:1.0.0]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [service.jar:1.0.0]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [service.jar:1.0.0]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [service.jar:1.0.0]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [service.jar:1.0.0]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [service.jar:1.0.0]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [service.jar:1.0.0]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) [service.jar:1.0.0]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [service.jar:1.0.0]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [service.jar:1.0.0]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569) [service.jar:1.0.0]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549) [service.jar:1.0.0]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.NumberFormatException: For input string: "7310155621"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:68) ~[?:?]at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:770) ~[?:?]
	at org.veupathdb.service.eda.ss.model.ResultSetUtils.getIntegerFromString(ResultSetUtils.java:23) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ss.model.VariableResultSetUtils.createValueVarFromResultSet(VariableResultSetUtils.java:159) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ss.model.VariableResultSetUtils.createVariableFromResultSet(VariableResultSetUtils.java:108) ~[service.jar:1.0.0]
	at org.veupathdb.service.eda.ss.model.VariableResultSetUtils.lambda$getEntityVariables$0(VariableResultSetUtils.java:70) ~[service.jar:1.0.0]
	at org.gusdb.fgputil.db.runner.SQLRunnerExecutors$QueryExecutor.handleResult(SQLRunnerExecutors.java:258) ~[service.jar:1.0.0]
	at org.gusdb.fgputil.db.runner.SQLRunner.executeSql(SQLRunner.java:380) ~[service.jar:1.0.0]
	... 35 more`

**Comment by d-callan** [comment]
above may have been to using rm41910. if not reproducible on eda-inc, please ignore that case.
