### ISSUE TITLE
why host unreachable?

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/EdaSubsettingService#94]
grep for "Host is unreachable"in container logs  and you get it in several services, 
eg eda compute service getting the message (https://github.com/VEuPathDB/service-eda-compute/issues/41) seems to be due to the acctdb not responding for 15mn..

subsetting is one of them.. wondering what it means. 
Also unclear what the UX is.. 

2023-02-04 17:33:46.530 [rid:7XcIO] DEBUG AuthFilter:171 - Request authenticated as a registered user
2023-02-04 17:33:46.530 [rid:7XcIO] INFO  ClientUtil:69 - Will send following GET request to http://dataset-access-internal:80/permissions
2023-02-04 17:33:47.531 [rid:2ODAh] ERROR StudiesService:155 - Unable to deliver distribution response
 java.lang.RuntimeException: Unable to read permissions response
	at org.veupathdb.service.eda.common.client.DatasetAccessClient.getStudyDatasetInfoMapForUser(DatasetAccessClient.java:109) ~[service.jar:3.5.2]
	at org.veupathdb.service.eda.common.client.DatasetAccessClient.getStudyDatasetInfo(DatasetAccessClient.java:122) ~[service.jar:3.5.2]
	at org.veupathdb.service.eda.common.client.DatasetAccessClient.getStudyAccess(DatasetAccessClient.java:144) ~[service.jar:3.5.2]
	at org.veupathdb.service.eda.common.auth.StudyAccess.confirmPermission(StudyAccess.java:57) ~[service.jar:3.5.2]
	at org.veupathdb.service.eda.ss.service.StudiesService.checkPerms(StudiesService.java:322) ~[service.jar:3.5.2]
	at org.veupathdb.service.eda.ss.service.StudiesService.postStudiesEntitiesVariablesDistributionByStudyIdAndEntityIdAndVariableId(StudiesService.java:132) ~[service.jar:3.5.2]

**Comment by aurreco-uga** [comment]
closing, old
